plugins {
    id 'com.github.johnrengelman.shadow'
}

loom {
    forge {
        mixinConfig "super_resolution.mixins.json"
        mixinConfig "super_resolution-forge.mixins.json"
        mixinConfig "super_resolution-forge-compat.mixins.json"
    }
}

architectury {
    platformSetupLoomIde()
    forge()
}
configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common

    // Files in this configuration will be bundled into your mod using the Shadow plugin.
    // Don't use the `shadow` configuration from the plugin itself as it's meant for excluding files.
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

repositories {
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases'
    }
}

dependencies {
    forge "net.minecraftforge:forge:$rootProject.forge_version"
    modImplementation "dev.architectury:architectury-forge:$rootProject.architectury_api_version"
    common(project(path: ':common', configuration: 'namedElements')) { transitive false }
    shadowBundle(project(path: ":common", configuration: "transformProductionForge"))
    modImplementation fileTree(dir: 'libs', include: ['*.jar'])
    forgeRuntimeLibrary fileTree(dir: 'libs', include: ['commons-math3-3.6.1.jar', 'jcpp-1.4.14.jar', 'luaj-core-3.0.3.jar', 'luaj-jse-3.0.3.jar'])
    modImplementation("maven.modrinth:timeless-and-classics-zero:1.1.4-hotfix-forge,1.20.1")
    modCompileOnly "dev.architectury:architectury:$rootProject.architectury_api_version"
    implementation("io.github.spair:imgui-java-app:1.87.5")
    implementation("io.github.spair:imgui-java-binding:1.87.5")
    implementation("io.github.spair:imgui-java-lwjgl3:1.87.5")

    forgeRuntimeLibrary "io.github.spair:imgui-java-app:1.87.5"
    forgeRuntimeLibrary "io.github.spair:imgui-java-binding:1.87.5"
    forgeRuntimeLibrary "io.github.spair:imgui-java-lwjgl3:1.87.5"

    implementation("org.lwjgl:lwjgl-vulkan:$lwjglVersion")
    forgeRuntimeLibrary("org.lwjgl:lwjgl-vulkan:$lwjglVersion")
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.1"))
    implementation("io.github.llamalad7:mixinextras-forge:0.4.1")
    include("org.lwjgl:lwjgl-vulkan:$lwjglVersion")
}

processResources {
    inputs.property 'version', project.version

    filesMatching('META-INF/mods.toml') {
        expand version: project.version
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    input.set shadowJar.archiveFile
}